version: '3.9'

services:
    postgres:
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=paw
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - postgres
        restart: unless-stopped

    postgres-grpc:
        build: .
        container_name: postgres-grpc
        image: ghcr.io/masudur-rahman/pawsitively-purrfect:latest
        command:
            - 'grpc-serve'
            - --config=/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        ports:
            - "8080:8080"
        volumes:
            - ./configs/.pawsitively-purrfect-grpc.yaml:/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        depends_on:
            - postgres
        networks:
            - postgres
            - postgres-grpc
        restart: unless-stopped

    pawsitively-purrfect:
        build: .
        container_name: pawsitively-purrfect
        image: ghcr.io/masudur-rahman/pawsitively-purrfect:latest
        command:
            - 'serve'
            - --config=/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        ports:
            - "62783:62783"
        depends_on:
            - postgres-grpc
        volumes:
            - ./configs/.pawsitively-purrfect-grpc.yaml:/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        networks:
            - postgres
            - postgres-grpc
        links:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge
    postgres-grpc:
        driver: bridge
volumes:
    postgres:
        driver: local
