version: '3.3'

services:
    arangodb:
        container_name: arangodb
        image: arangodb:3.8.4
#        platform: linux/arm64
        environment:
            ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD:-admin}
        volumes:
            - arangodb:/var/lib/arangodb3
        ports:
            - "8529:8529"
        networks:
            - arangodb
        restart: unless-stopped

    pawsitively-purrfect:
        build: .
        container_name: pawsitively-purrfect
        image: pawsitively-purrfect:latest
        depends_on:
            - arangodb
        volumes:
            - ./configs/.pawsitively-purrfect.yaml:/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        ports:
            - "62783:62783"
        networks:
            - arangodb
        links:
            - arangodb
        command: 'serve'
        restart: unless-stopped

networks:
    arangodb:
        driver: bridge
volumes:
    arangodb:

