version: '3.9'

services:
    arangodb:
        container_name: arangodb
        image: arangodb:3.10
        # platform: linux/arm64/v8
        environment:
            ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD:-admin}
        volumes:
            - arangodb:/var/lib/arangodb3
        ports:
            - "8529:8529"
        networks:
            - arangodb
        restart: unless-stopped

    pawsitively-purrfect:
        build: .
        container_name: pawsitively-purrfect
        image: ghcr.io/masudur-rahman/pawsitively-purrfect:latest
        command:
            - 'serve'
            - --config=/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        depends_on:
            - arangodb
        volumes:
            - ./configs/.pawsitively-purrfect.yaml:/etc/pawsitively-purrfect/configs/.pawsitively-purrfect.yaml
        ports:
            - "62783:62783"
        networks:
            - arangodb
        links:
            - arangodb
        restart: unless-stopped

networks:
    arangodb:
        driver: bridge
volumes:
    arangodb:

