server:
    host: 0.0.0.0
    port: 8888
    domain: pawsitively.purrfect

database:
    type: arangodb
    arangodb:
        host: "localhost"
        port: "8529"
        user: "root"
        password: "admin"
        name: "_system"

session:
    name: pawsitively_purrfect
    httpOnly: true
    csrfSecret: zjj0edXEmR1ntL22AizBDtejhNFP16u9Zl5MZZGmEwI=
    csrfHeader: "X-CSRF-Token"
    csrfForm: "_csrf"
    sessionKey: "userID"
