server:
    host: 0.0.0.0
    port: 62783
    domain: pawsitively.purrfect

grpc:
    serverHost: 0.0.0.0
    clientHost: localhost
    port: 8080

database:
#    type: arangodb
    type: postgres
    arangodb:
        host: "localhost"
        port: "8529"
        user: "root"
        password: "admin"
        name: "_system"
    postgres:
        host: localhost
        port: 5432
        user: postgres
        password: postgres
        name: paw
        sslmode: disable

session:
    name: pawsitively_purrfect
    httpOnly: true
    csrfSecret: zjj0edXEmR1ntL22AizBDtejhNFP16u9Zl5MZZGmEwI=
    csrfHeader: "X-CSRF-Token"
    csrfForm: "_csrf"
    sessionKey: "userID"
